import pyautogui
import time
def is_system_active():
    # Get the current mouse position
    x, y = pyautogui.position()

    # Wait for a short moment
    time.sleep(1)

    # Check if the mouse has moved from its original position
    new_x, new_y = pyautogui.position()
    if new_x != x or new_y != y:
        return True  # Mouse has moved, system is active
    else:
        return False  # Mouse has not moved, system is idle

# Example usage:
while True:
    time.sleep(5)
    if is_system_active():
        print("System is active")
    else:
        print("System is idle")

    # first any file  
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'up')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.keyDown('ctrl')
    pyautogui.press('j')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)
    pyautogui.hotkey('command', 'fn', 'down')
    time.sleep(5)



          
    time.sleep(10)  # Check every 10 seconds

    
      


